from __future__ import annotations

PLUGIN_NAME = "quotes"
SCHEMA_VERSION = 2
DUPLICATE_IMAGE_MESSAGE = "语录图片已存在"
GROUPS_DIRNAME = "groups"
IMAGES_DIRNAME = "images"
CACHE_DIRNAME = "cache"
IMAGE_INDEX_FILENAME = "image_index.json"
QUOTES_FILENAME = "quotes.json"
LEGACY_QUOTES_BAK_SUFFIX = ".bak"
DEFAULT_DHASH_THRESHOLD = 4
DEFAULT_DHASH_SIZE = 8
DEFAULT_ASPECT_RATIO_TOLERANCE = 0.08
